# Generated by Django 5.1.2 on 2024-11-02 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_publication_est_approuve_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_reçus', to=settings.AUTH_USER_MODEL)),
                ('expéditeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyés', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
