# Generated by Django 5.1.2 on 2024-11-02 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contenu',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
