# Generated by Django 5.1.2 on 2024-11-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_profile_nom_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='date_creation',
            new_name='date_pub',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='auteur',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='est_approuve',
        ),
        migrations.AlterField(
            model_name='publication',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/'),
        ),
    ]
