# Generated by Django 5.1.2 on 2024-11-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_rename_date_creation_publication_date_pub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='est_approuve',
            field=models.BooleanField(default=False),
        ),
    ]
