# Generated by Django 5.1.2 on 2024-11-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_auteur_date_inscription_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='created_at',
        ),
    ]
