# Generated by Django 5.1.2 on 2024-11-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_remove_follow_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
